import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillPhone, AiOutlineMail, AiFillTwitterCircle, AiFillGithub, AiFillLinkedin } from 'react-icons/ai';
import { useState } from 'react';
import Image from 'next/image';
import selfImage from '../images/myselfRemoved.png';
import csharp from '../images/csharp.png';
import css from '../images/css.png';
import html from '../images/html.png';
import javascript from '../images/javascript.png';
import reactLogo from '../images/react.png';
import node from '../images/node.png';
import python from '../images/python.png';
import tailwind from '../images/tailwind.png';
import sql from '../images/sql.png';
import oracle from '../images/oracle.png';
import java from '../images/java.png';
import php from '../images/php.png';
import git from '../images/git.png';
import portfolioProject from '../images/portfolioProject.png';
import mbProject from '../images/mbProject.png';

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Tyler Ferreira Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* Icon created by Icon mania - Flaticon */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section id='slide' className='min-h-screen'>
          <nav className='pt-10 md:pb-10 md:mb-3 flex justify-between sticky top-0'>
            <div className='flex'>
            <a href='tel:905-515-1651' className='mobile cursor-pointer bg-gradient-to-r from-fuchsia-700 to-purple-700 text-4xl text-white p-2 shadow-md dark:shadow-fuchsia-900 rounded-lg'><AiFillPhone/></a>
              <a href='mailto:tyler.ferreira1@mohawkcollege.ca' className='mobile cursor-pointer bg-gradient-to-r from-fuchsia-700 to-purple-700 text-4xl text-white p-2 mx-5 shadow-md dark:shadow-fuchsia-900 rounded-lg'><AiOutlineMail/></a>
              <a href='tel:905-515-1651' className='desktop cursor-pointer bg-gradient-to-r from-fuchsia-700 to-purple-700 text-xl text-white p-2 shadow-md dark:shadow-fuchsia-900 rounded-lg'>905-515-1651</a>
              <a href='mailto:tyler.ferreira1@mohawkcollege.ca' className='desktop cursor-pointer bg-gradient-to-r from-fuchsia-700 to-purple-700 text-xl text-white p-2 mx-5 shadow-md dark:shadow-fuchsia-900 rounded-lg'>Tyler.ferreira1@mohawkcollege.ca</a>
            </div>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='animate-bounce cursor-pointer text-2xl dark:text-white'/></li>
              <li><a href="https://1drv.ms/b/s!ApUrob8mlp8DjWg8g99n7Lo8TjTn?e=oNqpdu" target='_blank' className='text-xl bg-gradient-to-r from-fuchsia-700 to-purple-700 text-white px-4 py-2 rounded-md ml-8 shadow-lg dark:shadow-fuchsia-900'>Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-fuchsia-700 font-medium md:text-6xl dark:text-fuchsia-500 name'>TYLER FERREIRA</h2>
            {darkMode ? <span className='darkTitle text-2xl md:text-3xl dark:text-white'>Software Developer</span> : <span className='lightTitle text-2xl md:text-3xl dark:text-white'>Software Developer</span>}
            <p className='text-md py-5 text-gray-600 max-w-xl italic mx-auto md:text-xl dark:text-slate-300'>
              “Simplicity is the ultimate sophistication.” <br/>- Leonardo da Vinci
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-slate-400'>
            <a href="https://twitter.com/Tyler_Ferreira4" target='_blank'><AiFillTwitterCircle/></a>
            <a href="https://www.linkedin.com/in/tyler-ferreira" target='_blank'><AiFillLinkedin/></a>
            <a href="https://github.com/TylerFerreira" target='_blank'><AiFillGithub/></a>
          </div>
          <div className='relative mx-auto text-center bg-gradient-to-b from-fuchsia-700 rounded-full w-80 h-80 mt-20 overflow-hidden shadow-lg dark:shadow-fuchsia-900 md:h-96 md:w-96'>
           <Image src={selfImage} layout='fill' objectFit='cover' alt='Image of myself' priority></Image>
          </div>
          
        </section>

        <section>
          <div>
            <h3 className='text-3xl mt-20 py-1 dark:text-white'>Technical Skills</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-slate-200 md:max-w-4xl'>
              As a Full-Stack Developer, I have a strong foundation in various programming technologies and frameworks. I am proficient in front-end technologies as well as back-end technologies. Additionally, I have experience with agile methodologies and version control systems such as Git. With these skills, I am capable of developing robust and scalable applications that meet the needs of clients.
            </p>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg py-10 rounded-xl my-10 dark:bg-white dark:shadow-slate-500 lg:w-1/3'>
              <h3 className='text-lg font-medium pb-2'>Front-End</h3>
              <div className='flex justify-around md:flex-1'>
                <Image src={html} className='techImage' alt='technology logo'/>
                <Image src={css} className='techImage' alt='technology logo'/>
                <Image src={javascript} className='techImage' alt='technology logo'/>
                <Image src={reactLogo} className='techImage' alt='technology logo'/>
                <Image src={tailwind} className='techImage' alt='technology logo'/>
              </div>
            </div>

            <div className='text-center shadow-lg py-10 rounded-xl my-10 dark:bg-white dark:shadow-slate-500 lg:w-1/3'>
              <h3 className='text-lg font-medium pb-2'>Back-End</h3>
              <div className='flex justify-around md:flex-1'>
                <Image src={php} className='techImage' alt='technology logo'/>
                <Image src={sql} className='techImage' alt='technology logo'/>
                <Image src={oracle} className='techImage' alt='technology logo'/>
                <Image src={node} className='techImage' alt='technology logo'/>
              </div>
            </div>

            <div className='text-center shadow-lg py-10 rounded-xl my-10 dark:bg-white dark:shadow-slate-500 lg:w-1/3'>
              <h3 className='text-lg font-medium pb-2'>Miscellaneous</h3>
              <div className='flex justify-around md:flex-1'>
                <Image src={python} className='techImage' alt='technology logo'/>
                <Image src={java} className='techImage' alt='technology logo'/>
                <Image src={csharp} className='techImage' alt='technology logo'/>
                <Image src={git} className='techImage' alt='technology logo'/>
              </div>
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl mt-20 py-1 dark:text-white'>Projects</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-slate-200 md:max-w-4xl'>
              I have worked on a few projects that have allowed me to demonstrate my technical skills and creative problem-solving abilities. Each project presented a unique challenge that required me to develop innovative solutions and collaborate with team members to deliver high-quality results. These projects have given me the opportunity to work with a range of technologies and programming languages, including front-end and back-end development, database design, and version control. Through these experiences, I have gained valuable insight into the software development lifecycle and how to build effective solutions that meet the needs of clients.
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1 rounded-xl p-4 shadow-lg dark:shadow-slate-500 dark:bg-white flex flex-col justify-between'>
              <div>
                <Image src={portfolioProject} className='rounded-3xl shadow-2xl dark:shadow-slate-400' alt='web portfolio screenshot'/>
                <h4 className='pl-2 pt-5 text-2xl'>Web Portfolio</h4>
                <p className='pl-2 text-slate-600'>Portfolio website created using multiple front end technologies and frameworks. Hosted and deployed online with Vercel. Incorporates all professional design standards, created with mobile friendly responsive design.</p>
              </div>
              <div className='flex justify-between pt-5 projectImagesContainer'>
              <Image src={html} className='techImageProjects' alt='technology logo'/>
                <Image src={css} className='techImageProjects' alt='technology logo'/>
                <Image src={javascript} className='techImageProjects' alt='technology logo'/>
                <Image src={reactLogo} className='techImageProjects' alt='technology logo'/>
                <Image src={tailwind} className='techImageProjects' alt='technology logo'/>
                <Image src={node} className='techImageProjects' alt='technology logo'/>
                <Image src={git} className='techImageProjects' alt='technology logo'/>
                
              </div>
            </div>
            <div className='basis-1/3 flex-1 rounded-xl p-4 shadow-lg dark:shadow-slate-500 dark:bg-white flex flex-col justify-between'>
              <div>
                <Image src={mbProject} className='rounded-3xl shadow-2xl dark:shadow-slate-400' alt='mb website screenshot'/>
                <h4 className='pl-2 pt-5 text-2xl'>MB Property Management Portal</h4>
                <p className='pl-2 text-slate-600'>Full-stack web application for MB Property Management that provides landlords an easy way to manage their properties and allows tenants to access their information, report issues, and send messages to their landlord. This application aims to simplify property management and improve tenant-landlord communication. <span className='italic'>(Currently In Development)</span></p>
              </div>
              <div className='flex justify-between pt-5 sticky'>
                <Image src={html} className='techImageProjects' alt='technology logo'/>
                <Image src={css} className='techImageProjects' alt='technology logo'/>
                <Image src={javascript} className='techImageProjects' alt='technology logo'/>
                <Image src={reactLogo} className='techImageProjects' alt='technology logo'/>
                <Image src={node} className='techImageProjects' alt='technology logo'/>
                <Image src={git} className='techImageProjects' alt='technology logo'/>
                <Image src={php} className='techImageProjects' alt='technology logo'/>
                <Image src={sql} className='techImageProjects' alt='technology logo'/>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
